# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_auto_20171012_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
