# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_auto_20171013_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productimages',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
