# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_auto_20171014_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 17, 9, 7, 45, 509507)),
        ),
    ]
