# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_auto_20171018_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='sub_category',
        ),
    ]
