# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_auto_20171018_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='modify_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
