# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_auto_20171023_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentId', to='store_app.Category', verbose_name='Parent Category'),
        ),
    ]
