# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_auto_20171023_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='modify_date',
        ),
        migrations.AddField(
            model_name='category',
            name='modified_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
