# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_auto_20171023_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
