# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_auto_20171023_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modify_date',
            new_name='modified_date',
        ),
    ]
