# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0029_auto_20171024_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
    ]
