# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0030_auto_20171024_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
